#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : doxygen
Version  : 1.8.15
Release  : 12
URL      : https://sourceforge.net/projects/doxygen/files/rel-1.8.15/doxygen-1.8.15.src.tar.gz
Source0  : https://sourceforge.net/projects/doxygen/files/rel-1.8.15/doxygen-1.8.15.src.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 QPL-1.0
Requires: doxygen-bin = %{version}-%{release}
Requires: doxygen-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : bison-dev
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : flex
BuildRequires : glibc-dev
BuildRequires : llvm-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(sqlite3)
BuildRequires : python3
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : zlib-dev

%description
This directory contains a small subset of Troll-Tech's Qt library
The subset is enough to build the doxygen executable, but lacks many of
the features found in the Qt library. See http://www.trolltech.com
for the full package.

%package bin
Summary: bin components for the doxygen package.
Group: Binaries
Requires: doxygen-license = %{version}-%{release}

%description bin
bin components for the doxygen package.


%package license
Summary: license components for the doxygen package.
Group: Default

%description license
license components for the doxygen package.


%prep
%setup -q -n doxygen-1.8.15
cd %{_builddir}/doxygen-1.8.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604365266
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1604365266
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/doxygen
cp %{_builddir}/doxygen-1.8.15/LICENSE %{buildroot}/usr/share/package-licenses/doxygen/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/doxygen-1.8.15/qtools/LICENSE.GPL %{buildroot}/usr/share/package-licenses/doxygen/0e8a7a9afa6deae0946518b3666ee29da28dd6c5
cp %{_builddir}/doxygen-1.8.15/qtools/LICENSE.QPL %{buildroot}/usr/share/package-licenses/doxygen/50dde1b2673055896b2261b36e1f0a1f7609b797
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/doxygen

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/doxygen/0e8a7a9afa6deae0946518b3666ee29da28dd6c5
/usr/share/package-licenses/doxygen/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/doxygen/50dde1b2673055896b2261b36e1f0a1f7609b797
