#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : doxygen
Version  : 1.8.11
Release  : 1
URL      : http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.src.tar.gz
Source0  : http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.src.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 QPL-1.0
Requires: doxygen-bin
BuildRequires : bison
BuildRequires : cmake
BuildRequires : flex
BuildRequires : python-dev

%description
This directory contains a small subset of Troll-Tech's Qt library
The subset is enough to build the doxygen executable, but lacks many of
the features found in the Qt library. See http://www.trolltech.com
for the full package.

%package bin
Summary: bin components for the doxygen package.
Group: Binaries

%description bin
bin components for the doxygen package.


%prep
%setup -q -n doxygen-1.8.11

%build
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir}
make V=1  %{?_smp_mflags}
popd

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd clr-build ; make test ; popd

%install
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/doxygen
